version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MyAcad
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-backend:
    image: myacad-backend
    container_name: spring-backend
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/MyAcad?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      default:
        aliases:
          - backend 
    ports:
      - "8080:8080"

  angular-frontend:
    image: myacad-frontend
    container_name: angular-frontend
    ports:
      - "4200:80"

volumes:
  mysql_data: {}
