version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: mydb
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DBPASS}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  backend:
    build: ./backend
    container_name: spring-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
