version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: mydb
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: spring-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
